### ISSUE TITLE
Text Widget returns empty html

### ISSUE THREAD

**Issue by idesignzone** [benada002/wp-graphql-widgets#1]
Hello. Hope you are doing well. Thank you for the plugin. 
"html" data is very helpful as I won't need to fetch every widget individually and I can just loop the widgets within each sidebar. 
However text widget returns empty "html" data. 

`"html": "<div class=\"widget widget_text\">\t\t\t<div class=\"textwidget\"></div>\n\t\t</div>",`

**Comment by benada002** [comment]
Hi, thanks for the issue. I pushed a fix. Let me know if it works.

**Comment by idesignzone** [comment]
> Hi, thanks for the issue. I pushed a fix. Let me know if it works.

Issue is resolved. Thank you.
