### ISSUE TITLE
WPGraphQL release 6.1 returns type error

### ISSUE THREAD

**Issue by idesignzone** [benada002/wp-graphql-widgets#3]
After updating to WPGraphQL 6.1  start getting an error for widget types
`Error: __typename did not match an object type: WPWidgetBlock`

Last working version 1.5.9

**Comment by benada002** [comment]
Will look into it asap.

**Comment by benada002** [comment]
Do you've an example query for me? Or is the error happening without querying?

**Comment by idesignzone** [comment]
I am doing a sidebar query. 

```
  sidebar(sidebar: SIDEBAR) {
    afterSidebar
    afterTitle
    afterWidget
    beforeSidebar
    beforeTitle
    beforeWidget
    class
    databaseId
    description
    id
    name
    widgets {
      edges {
        cursor
        node {
          databaseId
        }
      }
    }
  }
```

and when I delete all widgets from sidebar it works. but adding any widget to sidebar results in this error
`Error: __typename did not match an object type: WPWidgetBlock`
problem start appearing after this release https://github.com/wp-graphql/wp-graphql/releases/tag/v1.6.0

Lets also note that latest Wordpress has introduced Block widgets and excluded traditional Widgets.

**Comment by benada002** [comment]
Which widgets/blocks are you using? I tried it with the image and text blocks and couldn't reproduce it with 1.6.1 and 1.6.2.

**Comment by idesignzone** [comment]
I made a minimum repo here https://github.com/idesignzone/gridsome-minimum.git

**Comment by benada002** [comment]
I'll try to look into it over the weekend.

**Comment by benada002** [comment]
I'm updating the dependencies. I've to resolve some errors before pushing it.

**Comment by benada002** [comment]
I updated the dependencies now in https://github.com/benada002/wp-graphql-widgets/pull/5 (branch: `fix-1.6-compat` ). Would you try if that's resolves the problem for you, since I can't reproduce it locally. Another question do have activated any other `wp-graphql` extensions/plugins? Because I noticed problems if you've activated one which has `wp-graphql > 1.6` as dependency.

**Comment by idesignzone** [comment]
Tested with 1.6.2 and 1.6.4 and works with no error. 
Thank you very much.

**Comment by benada002** [comment]
Thanks for testing. I'll merge it and release a new version tomorrow.
