### ISSUE TITLE
Invalid or incomplete introspection result

### ISSUE THREAD

**Issue by jacobdubail** [benada002/wp-graphql-widgets#4]
When I the visit GraphiQL IDE after activating this plugin, I see the following error in my console:

`Uncaught (in promise) Error: Invalid or incomplete introspection result. Ensure that you are passing "data" property of introspection response and no "errors" was returned alongside: undefined`

I believe this is a new issue as I was able to load the schema on another site before updating to WPGraphQL 1.6.2

**Comment by idesignzone** [comment]
Have you enabled Public Introspection in WPGraphQL settings?

**Comment by benada002** [comment]
The GraphiQL IDE (of wp-graphql) should work without public introspection enabled. Could you check the response (in developer tools > network should be a request to `index.php?graphql` ) for an error and if there is any comment it here?

**Comment by benada002** [comment]
@jacobdubail I updated the dependencies now (in master or https://github.com/benada002/wp-graphql-widgets/releases/tag/v0.0.3). Could you try if that resolves the issue for you?

**Comment by jacobdubail** [comment]
Thank you! This works. Much appreciated and sorry to go radio silent. I need to fix my GH notifications :/

**Comment by benada002** [comment]
No problem. Thanks for getting back.
